const ProductCompaniesList = [
  { name: "Apple", industry: "Technology" },
  { name: "Microsoft", industry: "Technology" },
  { name: "Google", industry: "Technology" },
  { name: "Amazon", industry: "E-commerce" },
  { name: "Facebook", industry: "Social Media" },
  { name: "Samsung", industry: "Electronics" },
  { name: "Sony", industry: "Electronics" },
  { name: "Intel", industry: "Semiconductors" },
  { name: "IBM", industry: "Technology" },
  { name: "NVIDIA", industry: "Semiconductors" },
  { name: "Adobe", industry: "Software" },
  { name: "Salesforce", industry: "Software" },
  { name: "Oracle", industry: "Technology" },
  { name: "SAP", industry: "Enterprise Software" },
  { name: "Cisco", industry: "Networking" },
  { name: "Dell", industry: "Electronics" },
  { name: "HP", industry: "Electronics" },
  { name: "Lenovo", industry: "Electronics" },
  { name: "Qualcomm", industry: "Semiconductors" },
  { name: "Uber", industry: "Transportation" },
  { name: "Lyft", industry: "Transportation" },
  { name: "Zoom", industry: "Technology" },
  { name: "Spotify", industry: "Entertainment" },
  { name: "Netflix", industry: "Entertainment" },
  { name: "Dropbox", industry: "Cloud Storage" },
  { name: "Slack", industry: "Communication" },
  { name: "Atlassian", industry: "Software" },
  { name: "GitHub", industry: "Software" },
  { name: "Trello", industry: "Productivity" },
  { name: "Evernote", industry: "Productivity" },
  { name: "Notion", industry: "Productivity" },
  { name: "Stripe", industry: "FinTech" },
  { name: "PayPal", industry: "FinTech" },
  { name: "Square", industry: "FinTech" },
  { name: "Shopify", industry: "E-commerce" },
  { name: "Magento", industry: "E-commerce" },
  { name: "WooCommerce", industry: "E-commerce" },
  { name: "Salesforce", industry: "CRM" },
  { name: "HubSpot", industry: "CRM" },
  { name: "Zendesk", industry: "Customer Service" },
  { name: "ServiceNow", industry: "IT Service Management" },
  { name: "Tableau", industry: "Data Analytics" },
  { name: "Power BI", industry: "Data Analytics" },
  { name: "Snowflake", industry: "Data Warehousing" },
  { name: "Palantir", industry: "Data Analytics" },
  { name: "Splunk", industry: "Data Analytics" },
  { name: "Elastic", industry: "Search and Analytics" },
  { name: "Datadog", industry: "Monitoring" },
  { name: "New Relic", industry: "Monitoring" },
  { name: "GitLab", industry: "Software" },
  { name: "Jira", industry: "Project Management" },
  { name: "Asana", industry: "Productivity" },
  { name: "Monday.com", industry: "Productivity" },
  { name: "Basecamp", industry: "Project Management" },
  { name: "Smartsheet", industry: "Productivity" },
  { name: "Confluence", industry: "Documentation" },
  { name: "BambooHR", industry: "HR Software" },
  { name: "Workday", industry: "HR Software" },
  { name: "Ultimate Software", industry: "HR Software" },
  { name: "ADP", industry: "HR Software" },
  { name: "Ceridian", industry: "HR Software" },
  { name: "SuccessFactors", industry: "HR Software" },
  { name: "Workforce", industry: "HR Software" },
  { name: "Oracle HCM", industry: "HR Software" },
  { name: "Rippling", industry: "HR Software" },
  { name: "Gusto", industry: "HR Software" },
  { name: "Zenefits", industry: "HR Software" },
  { name: "Namely", industry: "HR Software" },
  { name: "Paycor", industry: "HR Software" },
  { name: "Justworks", industry: "HR Software" },
  { name: "BambooHR", industry: "HR Software" },
  { name: "Deputy", industry: "Workforce Management" },
  { name: "When I Work", industry: "Workforce Management" },
  { name: "7shifts", industry: "Workforce Management" },
  { name: "Homebase", industry: "Workforce Management" },
  { name: "Kronos", industry: "Workforce Management" },
  { name: "TimeClock Plus", industry: "Workforce Management" },
  { name: "Clockify", industry: "Time Tracking" },
  { name: "Toggl", industry: "Time Tracking" },
  { name: "Harvest", industry: "Time Tracking" },
  { name: "Timely", industry: "Time Tracking" },
  { name: "RescueTime", industry: "Time Tracking" },
  { name: "Toggl Track", industry: "Time Tracking" },
  { name: "Hours", industry: "Time Tracking" },
  { name: "ClickTime", industry: "Time Tracking" },
  { name: "Everhour", industry: "Time Tracking" },
  { name: "Hubstaff", industry: "Time Tracking" },
  { name: "Traqq", industry: "Time Tracking" },
  { name: "Clockify", industry: "Time Tracking" },
  { name: "Time Doctor", industry: "Time Tracking" },
  { name: "Mavenlink", industry: "Project Management" },
  { name: "Wrike", industry: "Project Management" },
  { name: "Clarizen", industry: "Project Management" },
  { name: "Celoxis", industry: "Project Management" },
  { name: "Teamwork", industry: "Project Management" },
  { name: "Airtable", industry: "Project Management" },
  { name: "ClickUp", industry: "Project Management" },
  { name: "Zoho Projects", industry: "Project Management" },
  { name: "Proofhub", industry: "Project Management" },
  { name: "ProjectManager.com", industry: "Project Management" },
  { name: "Scoro", industry: "Project Management" },
  { name: "HubSpot CRM", industry: "CRM" },
  { name: "Pipedrive", industry: "CRM" },
  { name: "Freshsales", industry: "CRM" },
  { name: "Agile CRM", industry: "CRM" },
  { name: "Close", industry: "CRM" },
  { name: "Copper", industry: "CRM" },
  { name: "Insightly", industry: "CRM" },
  { name: "Nimble", industry: "CRM" },
  { name: "Less Annoying CRM", industry: "CRM" },
  { name: "Salesflare", industry: "CRM" },
  { name: "Vtiger CRM", industry: "CRM" },
  { name: "Highrise", industry: "CRM" },
  { name: "Streak", industry: "CRM" },
  { name: "Sage CRM", industry: "CRM" },
  { name: "SugarCRM", industry: "CRM" },
  { name: "Odoo CRM", industry: "CRM" },
  { name: "PipelineDeals", industry: "CRM" },
  { name: "Zoho CRM", industry: "CRM" },
  { name: "Base CRM", industry: "CRM" },
  { name: "Monday.com", industry: "Project Management" },
  { name: "Teamwork", industry: "Project Management" },
  { name: "Airtable", industry: "Project Management" },
  { name: "ClickUp", industry: "Project Management" },
  { name: "Zoho Projects", industry: "Project Management" },
  { name: "Proofhub", industry: "Project Management" },
  { name: "Scoro", industry: "Project Management" },
  { name: "Asana", industry: "Project Management" },
  { name: "Wrike", industry: "Project Management" },
  { name: "Mavenlink", industry: "Project Management" },
  { name: "Clarizen", industry: "Project Management" },
  { name: "Celoxis", industry: "Project Management" },
  { name: "Workfront", industry: "Project Management" },
  { name: "Smartsheet", industry: "Project Management" },
];

export default ProductCompaniesList;
