const SoftwareList = [
  { name: "Photoshop", company: "Adobe", version: "25.0" },
  { name: "Illustrator", company: "Adobe", version: "28.0" },
  { name: "Visual Studio Code", company: "Microsoft", version: "1.82" },
  { name: "Windows", company: "Microsoft", version: "11.0" },
  { name: "Node.js", company: "OpenJS Foundation", version: "20.6" },
  { name: "React", company: "Meta", version: "18.2.0" },
  { name: "MongoDB", company: "MongoDB Inc.", version: "6.0" },
  { name: "Docker", company: "Docker Inc.", version: "24.0" },
  {
    name: "Kubernetes",
    company: "Cloud Native Computing Foundation",
    version: "1.28",
  },
  { name: "Slack", company: "Slack Technologies", version: "4.33" },
  { name: "Zoom", company: "Zoom Video Communications", version: "5.16" },
  { name: "Git", company: "Software Freedom Conservancy", version: "2.42" },
  { name: "GitHub Desktop", company: "GitHub", version: "3.3" },
  { name: "Figma", company: "Figma Inc.", version: "116.8" },
  { name: "Chrome", company: "Google", version: "117.0" },
  { name: "Firefox", company: "Mozilla", version: "118.0" },
  { name: "Safari", company: "Apple", version: "17.0" },
  { name: "iOS", company: "Apple", version: "17.0" },
  { name: "Android", company: "Google", version: "14.0" },
  { name: "TypeScript", company: "Microsoft", version: "5.2" },
  { name: "Jira", company: "Atlassian", version: "9.6" },
  { name: "Trello", company: "Atlassian", version: "3.1" },
  { name: "Bitbucket", company: "Atlassian", version: "7.21" },
  { name: "MySQL", company: "Oracle", version: "8.0.34" },
  {
    name: "PostgreSQL",
    company: "PostgreSQL Global Development Group",
    version: "16.0",
  },
  { name: "SQLite", company: "SQLite", version: "3.43" },
  { name: "VS Code", company: "Microsoft", version: "1.82" },
  { name: "OpenAI API", company: "OpenAI", version: "2024.09" },
  { name: "TensorFlow", company: "Google", version: "2.14" },
  { name: "PyTorch", company: "Meta", version: "2.1" },
  { name: "Numpy", company: "NumPy Developers", version: "1.26" },
  { name: "Pandas", company: "Pandas Development Team", version: "2.1" },
  { name: "Jupyter", company: "Project Jupyter", version: "4.0" },
  { name: "Anaconda", company: "Anaconda Inc.", version: "2023.09" },
  { name: "Blender", company: "Blender Foundation", version: "3.6" },
  { name: "Unity", company: "Unity Technologies", version: "2023.1" },
  { name: "Unreal Engine", company: "Epic Games", version: "5.3" },
  { name: "Sketch", company: "Sketch B.V.", version: "96.0" },
  { name: "Inkscape", company: "Inkscape Project", version: "1.3" },
  { name: "Xcode", company: "Apple", version: "15.0" },
  { name: "JetBrains IntelliJ IDEA", company: "JetBrains", version: "2023.2" },
  { name: "PyCharm", company: "JetBrains", version: "2023.2" },
  { name: "WebStorm", company: "JetBrains", version: "2023.2" },
  { name: "Sublime Text", company: "Sublime HQ", version: "4.4152" },
  { name: "Notion", company: "Notion Labs", version: "2.26" },
  { name: "LibreOffice", company: "The Document Foundation", version: "7.6" },
  { name: "Apache OpenOffice", company: "Apache", version: "4.1.14" },
  { name: "Vim", company: "Bram Moolenaar", version: "9.0" },
  { name: "Emacs", company: "GNU Project", version: "28.2" },
  { name: "Discord", company: "Discord Inc.", version: "1.0.9016" },
  { name: "Spotify", company: "Spotify", version: "8.8" },
];

export default SoftwareList;
